### PR TITLE
Make footer component usable in all generated files

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Hey @diegonvs,

I saw some problems:

Home: screen shot 2018-03-15 at 4 00 18 pm

Documentation: screen shot 2018-03-15 at 4 00 14 pm

**Comment by jbalsas** [comment]
Hey @zenorocha, do you think this is fixed?

@diegonvs, @matuzalemsteles, how should I go on to test and verify this before merging? I haven't been that involved in electric development so far.

**Comment by jbalsas** [comment]
Merging to `develop` so we can test there with everything else on top!

**Pull request merged**
