### PR TITLE
Add base option for adding a custom base path to all urls

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@Robert-Frampton Just updated and getting this error:

Users might have to run this command `sudo rm /usr/local/lib/node_modules/electric-cli/node_modules/gh-pages/.cache/*` if getting the below error:

image

**Comment by Robert-Frampton** [comment]
@protoEvangelion does this happen every time you deploy?

**Comment by protoEvangelion** [comment]
Every time after updating Electric it happened with `electric deploy` until I removed the gh-pages module cache.

**Comment by Robert-Frampton** [comment]
Do you have to run `sudo` a lot when installing global modules?

**Comment by protoEvangelion** [comment]
Yes I do (on linux) ha

**Comment by Robert-Frampton** [comment]
Yeah, I think this is due to file permissions. If you set up your npm environement differently so that you don't have to have admin permissions for your global `node_modules` directory it should resolve that issue.

Check out [npm's docs](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory) for how to do so.

**Comment by protoEvangelion** [comment]
Thanks!

**Pull request merged**
