### PR TITLE
Adds support for customizing the main folder name for unZip export | Fixes #123

### LINKED ISSUE #123: Provide API to customize the repo download unZip directory with generate API
hey @zenorocha, for use cases in a monorepo like Clay that the main folder is `packages` and by default in Electric is the `src` folder. Maybe we should provide an API to customize this, what do you think? Makes sense to you?

See https://github.com/electricjs/electric/blob/master/packages/electric/lib/download.js#L74

### PR DESCRIPTION
**Pull request by matuzalemsteles**
> I did not think of a better name for this API, please if you have something better in mind, feel free to.

### New
* Adds to `apiConfig.project` **mainFolderName** to customize the main project folder for extraction.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, what about `srcFolder` or `srcPath` or `pathSrc`?

**Comment by matuzalemsteles** [comment]
Hey @jbalsas , `srcFolder` looks good to me, what do you think?

**Comment by jbalsas** [comment]
👍 @zenorocha, any particular preference?

**Comment by zenorocha** [comment]
I'd vote for `srcPath` which matches the pattern we're using here:

screen shot 2018-03-02 at 7 40 50 pm

> https://electricjs.com/docs/configuration/#options

**Comment by matuzalemsteles** [comment]
Hey @zenorocha, looks good to me, @jbalsas what do you think?

**Comment by jbalsas** [comment]
Sure, sounds good to me. Can you go ahead and change this, @matuzalemsteles?

**Comment by jbalsas** [comment]
Merged, thanks!

@zenorocha, I haven't released electric so far, so I'm not sure if we're following any particular workflow. Can you take care of this one, or let me know how to proceed from now on?

Thanks!

**Pull request merged**
